//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Example.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WeatherSummaries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherSummaries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Example.Resources.WeatherSummaries", typeof(WeatherSummaries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balmy.
        /// </summary>
        internal static string Balmy {
            get {
                return ResourceManager.GetString("Balmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracing.
        /// </summary>
        internal static string Bracing {
            get {
                return ResourceManager.GetString("Bracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilly.
        /// </summary>
        internal static string Chilly {
            get {
                return ResourceManager.GetString("Chilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        internal static string Cool {
            get {
                return ResourceManager.GetString("Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing.
        /// </summary>
        internal static string Freezing {
            get {
                return ResourceManager.GetString("Freezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        internal static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mild.
        /// </summary>
        internal static string Mild {
            get {
                return ResourceManager.GetString("Mild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorching.
        /// </summary>
        internal static string Scorching {
            get {
                return ResourceManager.GetString("Scorching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweltering.
        /// </summary>
        internal static string Sweltering {
            get {
                return ResourceManager.GetString("Sweltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        internal static string Warm {
            get {
                return ResourceManager.GetString("Warm", resourceCulture);
            }
        }
    }
}
